name: Build Kernel on GitHub Actions

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Making the Environment leaner
      run: sudo snap list && sudo snap remove firefox && sudo apt remove -y snapd

    - name: Update Environment
      run: sudo apt update -y

    - name: Install Dependencies
      run: |
        sudo apt install -y git-core gnupg build-essential zip \
        curl libarchive-tools flex \
        unzip python3 python3-pip python3-dev \
        python-is-python3 ccache libncurses5-dev lzop \
        patchelf git-lfs ripgrep &> /dev/null
    
    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: 14
        platform: x64
    
    - name: Kernel-SU Next
      run: | 
        curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next-susfs/kernel/setup.sh" | bash -s next-susfs

    - name: Download Neutron Toolchain
      run: bash scripts/hani-ci.sh --tools

    - name: Build hanikrnl.
      run: bash scripts/hani-ci.sh --build

    - name: Prepare Flashable ZIP
      run: |
        lastcommit=$(git log -n 1 --pretty=format:'%h' | cut -c 1-7)
        ZIPNAME="4.19-hanikrnl.KSU-NEXT."$lastcommit"-chime-$(date '+%d.%m.%y-%H%M').zip" && echo "ZIPNAME=$ZIPNAME" >> $GITHUB_ENV
        git clone https://github.com/Dominium-Apum/AnyKernel3.git
        mkdir -p AnyKernel3
        cp out/arch/arm64/boot/Image AnyKernel3/
        cp out/arch/arm64/boot/dtbo.img AnyKernel3/
        cp out/arch/arm64/boot/dtb.img AnyKernel3/
        rm -f AnyKernel3/README.md 
        rm -rf AnyKernel3/.git
        find AnyKernel3/ -name "*placeholder*" -exec rm -rf {} +

    - name: Upload kernel
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ZIPNAME }}
        path: ./AnyKernel3/*
        compression-level: 9
