name: Build Kernel on GitHub Actions

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Making the Environment leaner
      run: sudo snap list && sudo snap remove firefox && sudo apt remove -y snapd

    - name: Update Environment
      run: sudo apt update -y

    - name: Install Dependencies
      run: |
        sudo apt install -y git-core gnupg build-essential zip \
        curl libarchive-tools flex \
        unzip python3 python3-pip python3-dev \
        python-is-python3 ccache libncurses5-dev lzop \
        patchelf git-lfs ripgrep &> /dev/null
      
    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: 11
        platform: x64

    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 10
          
    - name: Download Neutron Toolchain
      run: bash scripts/hani-ci.sh --tools

    - name: Build hanikrnl.
      run: bash scripts/hani-ci.sh --build

    - name: Upload kernel
      uses: actions/upload-artifact@v4
      with:
        name: hanikrnl-android
        path: 4.19-hanikrnl.android-*-chime*.zip
